### ISSUE TITLE
SphinxファイルがWindows環境でビルドできない

### ISSUE THREAD

**Issue by yk0nno** [zunda-cafe/zunda-cafe#13]
# Description
おそらくこの問題 -> http://yoyogisan.hatenablog.com/entry/2014/08/26/220352

# Detail
vi上で見ると問題ない(1文字として見える)がSakura上だと濁点が分裂して見える
![sakura-vi](https://user-images.githubusercontent.com/12147692/28277778-f5d56c64-6b55-11e7-932d-18013c525ab5.png)

Sphinxビルド時はSakuraと同じ挙動でパスを見に行くようで、日本語を含むsvgのパスが取れず、ビルドがエラーとなる
```
C:\zunda\zunda-cafe\source\vcs\git.rst:107: WARNING: image file not readable: vcs\images/Git�ɂЂƂ�t�@�C����\u309
9�������.svg
looking for now-outdated files... C:\zunda\zunda-cafe\source\vcs\git.rst:140: WARNING: image file not readable: vcs\images/Git�̃��[�L���N\u3099�e\u3099�B���N�g���Ƀt
�@�C����ǉ��������.svg
C:\zunda\zunda-cafe\source\vcs\git.rst:179: WARNING: image file not readable: vcs\images/Git��\u3099�X�e�[�V\u3099
���N\u3099���ꂽ���.svg
C:\zunda\zunda-cafe\source\vcs\git.rst:211: WARNING: image file not readable: vcs\images/Git��\u3099���z\u309a�V\u
3099�g���փt�@�C����R�~�b�g�������.svg
none found
```

# 解決策
@naninuneter55 の使用されたエディタが何か、ですが、回避可能であれば保存時の文字コードがMac固有UTF-8とならないよう設定可能でしょうか。
Sakuraのキャプチャ一行目、「images/Gitのローカルリポジトリ.svg」はこちらで打ち直してみたところ、notfoundは消えて無事ビルドできるようになりました。

**Comment by naninuneter55** [comment]
不具合報告ありがとうございます。
結局、Windows/Mac混在のチーム開発では、可能であれば日本語ファイル名は使用しないほうがよいということでしょう。後日ファイル名を英名に修正します。修正してWIndowsでエラーがないこと確認したらcloseします。
少し時間をください。

以下の手順のため日本語ファイル名になっています。エディタでファイル名を設定していません。

1. 「google図形描画」で絵を描き、絵の名前に日本語名を付ける（ex. Gitのローカルリポジトリ）
1. SVGファイルでダウンロードする。ダウンロードファイルのファイル名は絵の名前になる。（ex. Gitのローカルリポジトリ.svg）
1. ダウンロードをSphinxのimageフォルダにmvする。

**Comment by naninuneter55** [comment]
@maruhachi 日本語ファイル名を排除しました。再検証をお願いします。
